// Navajo Clan Database
const clansDatabase = [
    { navajo: "Adoots'osnii diné'é", english: "Narrow Gorge People", group: "Group 18 (Light Green)", type: "Adopted clan" },
    { navajo: "Ahi diné'é", english: "Fog", group: "Group 11 (Light Green)", type: "Hopi clan", hopi: "Pamoswungwa" },
    { navajo: "Anaashashí", english: "Santa Clara", group: "Group 12 (Light Green)", type: "Rio Grande Pueblo clan" },
    { navajo: "Áshįįhí", english: "Salt", group: "Group 7 (Brown)", type: "" },
    { navajo: "Áshįįhnii", english: "Salt People", group: "Group 7 (Brown)", type: "" },
    { navajo: "Atsá diné'é", english: "Eagle", group: "Group 11 (Light Green)", type: "Hopi clan", hopi: "Kwaawungwa" },
    { navajo: "Azee'tsoh Diné", english: "Big Medicine People", group: "Group 1 (White)", type: "" },
    { navajo: "Béésh bicha'ahii", english: "German", group: "Group 18 (Light Green)", type: "Adopted clan" },
    { navajo: "Bįįh Bitoodnii", english: "Deer Spring", group: "Group 3 (Yellow)", type: "" },
    { navajo: "Bįįh diné'é", english: "Deer", group: "Group 11 (Light Green)", type: "Hopi clan", hopi: "Alwungwa" },
    { navajo: "Bįįh diné'é Táchiiʼnii", english: "Deer People of the Red Running into the Water", group: "Group 6 (Red)", type: "" },
    { navajo: "Bįįh yíízh diné'é", english: "Little Deer People", group: "Group 18 (Light Green)", type: "Adopted clan" },
    { navajo: "Bįįhtsoh diné'é", english: "Big Deer People", group: "Group 18 (Light Green)", type: "Adopted clan" },
    { navajo: "Bįįhyáázh diné'é", english: "Little Deer People", group: "Group 3 (Yellow)", type: "" },
    { navajo: "Binííáadaałtsóázį", english: "Japanese", group: "Group 18 (Light Green)", type: "Adopted clan" },
    { navajo: "Bitáahánii", english: "Within His Cover", group: "Group 1 (White)", type: "" },
    { navajo: "Bitsiiáyisbizhii", english: "Chinese", group: "Group 18 (Light Green)", type: "Adopted clan" },
    { navajo: "Báyóodzin", english: "Paiutes", group: "Group 17 (Light Green)", type: "Uto-Aztecan clan" },
    { navajo: "Chishí Diné'é", english: "Chiricahua", group: "Group 10 (Light Green)", type: "Apache clan" },
    { navajo: "Dahmi", english: "Santa Ana", group: "Group 13 (Light Green)", type: "Jemez Pueblo clan" },
    { navajo: "Déeł diné'é", english: "Crane", group: "Group 11 (Light Green)", type: "Hopi clan", hopi: "Atokwungwa" },
    { navajo: "Deeshchii'nii", english: "Start at the Red Streak People", group: "Group 9 (Lavender)", type: "" },
    { navajo: "Dibé łizhiní", english: "Black Sheep", group: "Group 7 (Brown)", type: "" },
    { navajo: "Dichin diné'é", english: "Hunger People", group: "Group 18 (Light Green)", type: "Adopted clan" },
    { navajo: "Diizhíí", english: "Yavapai", group: "Group 16 (Light Green)", type: "Southern Arizona clan" },
    { navajo: "Dilzééhi", english: "Mohave", group: "Group 16 (Light Green)", type: "Southern Arizona clan" },
    { navajo: "Dįwózhii diné'é", english: "Greasewood", group: "Group 11 (Light Green)", type: "Hopi clan", hopi: "Tepwungwa" },
    { navajo: "Dólii diné'é", english: "Blue Bird", group: "Group 6 (Red)", type: "" },
    { navajo: "Dólii diné'é", english: "Bluebird", group: "Group 11 (Light Green)", type: "Hopi clan", hopi: "Torswungwa" },
    { navajo: "Doohatsáyíłtiáį", english: "Italian", group: "Group 18 (Light Green)", type: "Adopted clan" },
    { navajo: "Dzaanééz łanį", english: "Many Mules", group: "Group 4 (Black)", type: "" },
    { navajo: "Dziłghą́ʼí", english: "White Mountain", group: "Group 10 (Light Green)", type: "Apache clan" },
    { navajo: "Dził ná'oodiłnii", english: "The Turning Mountain", group: "Group 2 (Blue)", type: "" },
    { navajo: "Dził ná'oodiłnii", english: "Turning Mountain", group: "Group 7 (Brown)", type: "" },
    { navajo: "Dził t'áa'nii", english: "Near the Mountain", group: "Group 1 (White)", type: "" },
    { navajo: "Dził tł'ahnii", english: "Mountain Cove", group: "Group 2 (Blue)", type: "" },
    { navajo: "Gah diné'é Táchiiʼnii", english: "Rabbit People of the Red Running into the Water", group: "Group 6 (Red)", type: "" },
    { navajo: "Gahtsoh diné'é", english: "Rabbit", group: "Group 11 (Light Green)", type: "Hopi clan", hopi: "Tapwungwa" },
    { navajo: "Ginitsoh xibáhí diné'é", english: "Grey Hawk", group: "Group 11 (Light Green)", type: "Hopi clan", hopi: "Masikwaywungwa" },
    { navajo: "Góóníinii", english: "Havasupai", group: "Group 16 (Light Green)", type: "Southern Arizona clan" },
    { navajo: "Haakʼoh", english: "Acoma", group: "Group 14 (Light Green)", type: "Mount Taylor Pueblo clan" },
    { navajo: "Hakʼaz dineʼé", english: "Eskimo", group: "Group 18 (Light Green)", type: "Adopted clan" },
    { navajo: "Halgai diné'é", english: "People of the Valley", group: "Group 1 (White)", type: "" },
    { navajo: "Haltsooį", english: "Meadow People", group: "Group 5 (Dark Green)", type: "" },
    { navajo: "Hashk'ąą hadzohí", english: "Yucca Fruit Strung Out", group: "Group 2 (Blue)", type: "" },
    { navajo: "Hashtł'ishnii", english: "Mud Clan", group: "Group 4 (Black)", type: "" },
    { navajo: "Honágháahnii", english: "One Who Walks Around", group: "Group 2 (Blue)", type: "" },
    { navajo: "Hooghan łanį", english: "Many Hogans", group: "Group 4 (Black)", type: "" },
    { navajo: "Iicháęh diné'é", english: "Moth People", group: "Group 18 (Light Green)", type: "Adopted clan" },
    { navajo: "Jaaáyaalóolii diné'é", english: "The Sticking Up Ears People", group: "Group 18 (Light Green)", type: "Adopted clan" },
    { navajo: "Jóhonaaʼéí diné'é", english: "Sun", group: "Group 11 (Light Green)", type: "Hopi clan", hopi: "Taawawungwa" },
    { navajo: "Kéʼhaʼátʼíinii", english: "The Foot Trails People", group: "Group 18 (Light Green)", type: "Adopted clan" },
    { navajo: "Kégiizhí", english: "Tohono Oʼodham", group: "Group 16 (Light Green)", type: "Southern Arizona clan" },
    { navajo: "Kéʼhaʼátʼíinii", english: "The Foot Trail People", group: "Group 8 (Orange)", type: "" },
    { navajo: "Kétłʼáhí", english: "Pima", group: "Group 16 (Light Green)", type: "Southern Arizona clan" },
    { navajo: "K'tsinį", english: "Dutch", group: "Group 18 (Light Green)", type: "Adopted clan" },
    { navajo: "Kʼaaʼ diné'é", english: "The Arrow People", group: "Group 3 (Yellow)", type: "" },
    { navajo: "Kʼaaʼ hiníanii", english: "The Living Arrow", group: "Group 3 (Yellow)", type: "" },
    { navajo: "Kʼos diné'é", english: "Cloud", group: "Group 11 (Light Green)", type: "Hopi clan", hopi: "Oomawaewungwa" },
    { navajo: "Kíawa", english: "Kiowa", group: "Group 18 (Light Green)", type: "Adopted clan" },
    { navajo: "Kin łichįį'nii", english: "Red House", group: "Group 9 (Lavender)", type: "" },
    { navajo: "Kin Łichíínii", english: "San Juan", group: "Group 12 (Light Green)", type: "Rio Grande Pueblo clan" },
    { navajo: "Kin Łigai diné'é", english: "Sandia", group: "Group 12 (Light Green)", type: "Rio Grande Pueblo clan" },
    { navajo: "Kin Łitsonii", english: "Yellow House", group: "Group 7 (Brown)", type: "" },
    { navajo: "Kin łitsonii diné'é", english: "Yellow House People", group: "Group 18 (Light Green)", type: "Adopted clan" },
    { navajo: "Kinyaa'áanii", english: "Towering House", group: "Group 1 (White)", type: "" },
    { navajo: "Kʼǫʼ diné'é", english: "Fire", group: "Group 11 (Light Green)", type: "Hopi clan" },
    { navajo: "Kʼaalógii diné'é", english: "Butterfly", group: "Group 11 (Light Green)", type: "Hopi clan", hopi: "Poovalwungwa" },
    { navajo: "Lók'aa' diné'é", english: "Reed People", group: "Group 4 (Black)", type: "" },
    { navajo: "Lókʼaaʼtsoh diné'é", english: "Bamboo", group: "Group 11 (Light Green)", type: "Hopi clan", hopi: "Paaqapwungwa" },
    { navajo: "Ma'ii tó", english: "Water Coyote", group: "Group 11 (Light Green)", type: "Hopi clan", hopi: "Paaeiswungwa" },
    { navajo: "Ma'ii Deeshgiizhnii", english: "Coyote Pass- Jemez", group: "Group 7 (Brown)", type: "" },
    { navajo: "Ma'ii diné'é", english: "Coyote", group: "Group 11 (Light Green)", type: "Hopi clan", hopi: "Iswungwa" },
    { navajo: "Maʼiideeshgiizhnii", english: "Jemez Pueblos", group: "Group 13 (Light Green)", type: "Jemez Pueblo clan" },
    { navajo: "Naʼesjéʼii diné'é", english: "Spider", group: "Group 11 (Light Green)", type: "Hopi clan", hopi: "Kookyangwungwa" },
    { navajo: "Naʼashqii diné'é", english: "Lizard", group: "Group 11 (Light Green)", type: "Hopi clan", hopi: "Kunkutswungwa" },
    { navajo: "Naadą́ą́' Dine'é", english: "Corn People", group: "Group 1 (White)", type: "" },
    { navajo: "Naadą́ą́' Dine'é", english: "Corn", group: "Group 11 (Light Green)", type: "Hopi clan", hopi: "Piikyaswungwa" },
    { navajo: "Naadą́ą́' Dine'é Tábąąhá", english: "Water Edge Corn", group: "Group 5 (Dark Green)", type: "" },
    { navajo: "Naakétł'ahí", english: "Flat Foot People - Tohono Oæodam", group: "Group 3 (Yellow)", type: "" },
    { navajo: "Naakai diné'é", english: "The Mexican People", group: "Group 8 (Orange)", type: "" },
    { navajo: "Naakaii łizhinii", english: "Negro", group: "Group 18 (Light Green)", type: "Adopted clan" },
    { navajo: "Naakaiiłbíhį", english: "Spanish", group: "Group 18 (Light Green)", type: "Adopted clan" },
    { navajo: "Naałínį", english: "Comanche/Sioux", group: "Group 18 (Light Green)", type: "Adopted clan" },
    { navajo: "Naaneesht'é'zhí Táchiiʼnii", english: "The Charcoal Streaked of the Red Running into the Water", group: "Group 6 (Red)", type: "" },
    { navajo: "Naashtʼézhí", english: "Zuni", group: "Group 15 (Light Green)", type: "Zuni clan" },
    { navajo: "Naasht'ézhí Dine'é Tábąąhá", english: "Water Edge Zuni", group: "Group 5 (Dark Green)", type: "" },
    { navajo: "Naasht'ezhí dine'é", english: "Zuni People", group: "Group 6 (Red)", type: "" },
    { navajo: "Naatoohí", english: "Isleta", group: "Group 12 (Light Green)", type: "Rio Grande Pueblo clan" },
    { navajo: "Naatsédlózhii diné'é", english: "Roadrunner", group: "Group 11 (Light Green)", type: "Hopi clan", hopi: "Posiwungwa" },
    { navajo: "Naayízí diné'é", english: "The Squash People", group: "Group 1 (White)", type: "" },
    { navajo: "Naayízí diné'é", english: "Squash", group: "Group 11 (Light Green)", type: "Hopi clan", hopi: "Paatangwungwa" },
    { navajo: "Nahashchʼidii diné'é", english: "Badger", group: "Group 11 (Light Green)", type: "Hopi clan", hopi: "Honanwungwa" },
    { navajo: "Nihóbáanii", english: "Gray Streaked Ends", group: "Group 2 (Blue)", type: "" },
    { navajo: "Nát'oh diné'é", english: "Tobacco People", group: "Group 6 (Red)", type: "" },
    { navajo: "Nát'oh diné'é", english: "Tobacco", group: "Group 11 (Light Green)", type: "Hopi clan", hopi: "Pipwungwa" },
    { navajo: "Nóódai", english: "Utes", group: "Group 17 (Light Green)", type: "Uto-Aztecan clan" },
    { navajo: "Nóoda'í diné'é", english: "Ute People", group: "Group 8 (Orange)", type: "" },
    { navajo: "Nóódaáį diné'é Táchiiʼnii", english: "The Ute People of the Red Running into the Water", group: "Group 6 (Red)", type: "" },
    { navajo: "Séí diné'é", english: "Sand", group: "Group 11 (Light Green)", type: "Hopi clan", hopi: "Tuwawungwa" },
    { navajo: "Séeíbeehooghanii", english: "San Felipe", group: "Group 12 (Light Green)", type: "Rio Grande Pueblo clan" },
    { navajo: "Shash diné'é", english: "Bear People", group: "Group 1 (White)", type: "" },
    { navajo: "Shash diné'é", english: "Bear", group: "Group 11 (Light Green)", type: "Hopi clan", hopi: "Honwungwa" },
    { navajo: "Shash diné'é / Naashashi", english: "The Bear People", group: "Group 9 (Lavender)", type: "" },
    { navajo: "Taáneeszahnii", english: "Tangle", group: "Group 2 (Blue)", type: "" },
    { navajo: "Táchiiʼnii", english: "Red Running into the Water", group: "Group 6 (Red)", type: "" },
    { navajo: "Tązhii diné'é", english: "Turkey People", group: "Group 1 (White)", type: "" },
    { navajo: "Tábąąhá", english: "Water Edge", group: "Group 5 (Dark Green)", type: "" },
    { navajo: "Tádidiin diné'é", english: "Corn Pollen People", group: "Group 18 (Light Green)", type: "Adopted clan" },
    { navajo: "Tł'ááshchí'í", english: "The Red Bottom People", group: "Group 9 (Lavender)", type: "" },
    { navajo: "Tłízí daalchí'í", english: "Red Goat", group: "Group 6 (Red)", type: "" },
    { navajo: "Tłízí łaní", english: "Many Goat", group: "Group 9 (Lavender)", type: "" },
    { navajo: "Tłízí łizhinį diné'é", english: "Black Goat People", group: "Group 18 (Light Green)", type: "Adopted clan" },
    { navajo: "Tłʼógi", english: "Zia Pueblos", group: "Group 13 (Light Green)", type: "Jemez Pueblo clan" },
    { navajo: "Tłʼógi diné'é", english: "Zia Pueblo", group: "Group 3 (Yellow)", type: "" },
    { navajo: "Tłʼoh Łikizhí diné'é", english: "Tesuque", group: "Group 12 (Light Green)", type: "Rio Grande Pueblo clan" },
    { navajo: "Tłʼish áníígíí diné'é", english: "Rattlesnake", group: "Group 11 (Light Green)", type: "Hopi clan", hopi: "Tsuaewungwa" },
    { navajo: "Tó aheedlįįnii", english: "The Water Flow Together", group: "Group 8 (Orange)", type: "" },
    { navajo: "Tó Baazhní'ázhí", english: "Two Who Come to the Water", group: "Group 3 (Yellow)", type: "" },
    { navajo: "Tó Baazhní'ázhí", english: "Two Who Came to the Water", group: "Group 5 (Dark Green)", type: "" },
    { navajo: "Tó diné'é", english: "Water", group: "Group 11 (Light Green)", type: "Hopi clan", hopi: "Patkiwungwa" },
    { navajo: "Tó tsohnii", english: "Big Water", group: "Group 4 (Black)", type: "" },
    { navajo: "Tó'áhání", english: "Near the Water", group: "Group 2 (Blue)", type: "" },
    { navajo: "Tóáíszóli diné'é", english: "The Light-Water People", group: "Group 18 (Light Green)", type: "Adopted clan" },
    { navajo: "Tódíchʼíiʼnii", english: "Bitter Water", group: "Group 3 (Yellow)", type: "" },
    { navajo: "Tódík'ǫ́zhí", english: "Salt Water", group: "Group 3 (Yellow)", type: "" },
    { navajo: "Tóhajilohnii", english: "Santa Domingo", group: "Group 12 (Light Green)", type: "Rio Grande Pueblo clan" },
    { navajo: "Tókʼánii biyázh dineʼé", english: "Acomita", group: "Group 14 (Light Green)", type: "Mount Taylor Pueblo clan" },
    { navajo: "Tókʼánii dineʼé", english: "Laguna", group: "Group 14 (Light Green)", type: "Mount Taylor Pueblo clan" },
    { navajo: "Tówołnii", english: "Taos", group: "Group 12 (Light Green)", type: "Rio Grande Pueblo clan" },
    { navajo: "Tsé deeshgiizhnii", english: "Rock Gap", group: "Group 4 (Black)", type: "" },
    { navajo: "Tsé nahabiłnii", english: "Sleep Rock People", group: "Group 9 (Lavender)", type: "" },
    { navajo: "Tsé nįjįkinį", english: "Honey Combed Rock or Cliff Dwellers", group: "Group 7 (Brown)", type: "" },
    { navajo: "Tséghá'di'nídínii diné'é", english: "Crystal Rock", group: "Group 3 (Yellow)", type: "" },
    { navajo: "Tsétakʼin", english: "San Ildefonso", group: "Group 12 (Light Green)", type: "Rio Grande Pueblo clan" },
    { navajo: "Ts'ah Yisk'idnii", english: "Sage Brush Hill", group: "Group 2 (Blue)", type: "" },
    { navajo: "Tsi'naajinii", english: "Black Streak Wood People", group: "Group 9 (Lavender)", type: "" },
    { navajo: "Tsídii yáłtiʼí diné'é", english: "Parrot", group: "Group 11 (Light Green)", type: "Hopi clan", hopi: "Kyarwungwa" },
    { navajo: "Tsidiiłbáhí diné'é", english: "Sparrow Hawk", group: "Group 11 (Light Green)", type: "Hopi clan", hopi: "Kyelwungwa" },
    { navajo: "Tsin yeenaáaloáii diné'é", english: "Tree Stretcher / Carries with Wooden Stick People", group: "Group 18 (Light Green)", type: "Adopted clan" },
    { navajo: "T'iis Ché'ébáanii", english: "Gray Cottonwood Extending Out", group: "Group 9 (Lavender)", type: "" },
    { navajo: "Yas diné'é", english: "Snow", group: "Group 11 (Light Green)", type: "Hopi clan", hopi: "Nuvaewungwa" },
    { navajo: "Yé'ii diné'é", english: "Giant People", group: "Group 6 (Red)", type: "" },
    { navajo: "Yoo'ó diné'é", english: "Bead People", group: "Group 3 (Yellow)", type: "" },
    { navajo: "Yoo'ó diné'é Tódíchʼíiʼnii", english: "The Bead People of Bitter Water", group: "Group 3 (Yellow)", type: "" }
];
